name: Deploy to EC2

on:
  push:
    branches:
      - main  # The branch to watch for changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: List all files in the workspace to verify directory structure
      - name: List all files for debugging
        run: ls -R .

      # Step 3: Copy files via SSH to the EC2 instance
      - name: Copy frontend and backend via SSH
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"  # Copy the entire repository or adjust as needed
          target: "/home/ec2-user/deployment-directory/"

      # Step 4: Run deployment script for frontend and backend on the EC2 instance
      - name: Run deployment script on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the backend directory, install dependencies, and build
            cd /home/ec2-user/deployment-directory/backend
            npm install
            npm run build
            pm2 restart backend-app-name  # Replace with your actual process manager and app name

            # Navigate to the frontend directory, install dependencies, and build
            cd /home/ec2-user/deployment-directory/frontend
            npm install
            npm run build
            pm2 serve build 3000 --name frontend-app-name  # Adjust this command as needed for serving the frontend
